FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on (default is 3000 for many Node.js apps)
EXPOSE 4008

# Define the command to run your application
CMD ["npm", "start"]